name: decap
channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - isort
  - pytest-cov
  - mypy
  - python=3.10.9
  - black
  - pytest
  - pandas
  - requests
  - prefect
  - notebook
  - nb_conda_kernels
  - fastparquet
  - python-snappy
  - pip:
      - google-cloud-storage
      - pip-chill
      - prefect-gcp
